- add-ons/yunikorn/Chart.yaml
Updating yunikorn from 0.11.0 to 0.12.2
> Update yunikorn version

- add-ons/prometheus/values.yaml
- chart/templates/prometheus.yaml
Fixes prometheus Application config and default values. 
> Updating prometheus values

- add-ons/traefik/Chart.yaml
- add-ons/vpa/Chart.yaml
- add-ons/vpa/values.yaml
- add-ons/yunikorn/Chart.yaml
Update traefik helm chart from 10.0.0 to 10.14.1
> Traefik update

- add-ons/vpa/Chart.yaml
- add-ons/vpa/values.yaml
- add-ons/yunikorn/Chart.yaml
updates the VPA helm chart and fixes a typo in the yunikorn chart description
> update VPA helm chart and fix typo in yunikorn chart description

- add-ons/prometheus/Chart.yaml
Updates the helm chart for Prometheus to version 15.3.0
> update prometheus helm chart version to 15.3.0

- add-ons/keda/Chart.yaml
Updates the helm chart for keda to 2.6.2
> Update keda helm chart

- add-ons/ingress-nginx/Chart.yaml
Updates the helm chart for ingress-nginx to 4.0.17
> Update nginx helm chart to 4.0.17

- chart/templates/keda.yaml
> fix keda namespace

- README.md
- chart/templates/argo-rollouts.yaml
- chart/templates/kube-state-metrics.yaml
- chart/templates/kubernetes-dashboard.yaml
- chart/values.yaml
> Renaming changes

- add-ons/aws-cloudwatch-metrics/Chart.yaml
- add-ons/aws-cloudwatch-metrics/values.yaml
- chart/templates/aws-cloudwatch-metrics.yaml
- chart/values.yaml
Adds https://github.com/aws-ia/terraform-ssp-amazon-eks/issues/35
ArgoCD GitOps config for AWS CloudWatch Metrics
> Add AWS CloudWatch Metrics Add-on

- chart/templates/ingress-nginx.yaml
Updating namespace to match blueprints module. 
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/ingress-nginx/locals.tf#L9
Update ingress-nginx namespace. 
> Update ingress-nginx namespace

- add-ons/appmesh-controller/Chart.yaml
- add-ons/aws-cloudwatch-metrics/Chart.yaml
- add-ons/aws-load-balancer-controller/Chart.yaml
- add-ons/gatekeeper/Chart.yaml
Update charts descriptions to match chart application
> Update charts descriptions to match chart application

- chart/templates/prometheus.yaml
> fix: update prometheus.yaml so it works with IRSA

- chart/templates/prometheus.yaml
change line 28 from sigV4 to sigv4 to match with prometheus chart value. I've tested on my side. thanks
my amazon email is victorgw@amazon.com pls let me know if you have any concern.
> typo error in prometheus template

- add-ons/aws-load-balancer-controller/Chart.yaml
> Fix typo in AWS Load Balancer Controller Chart.yaml

- add-ons/agones/Chart.yaml
- add-ons/argo-rollouts/Chart.yaml
- add-ons/aws-efs-csi-driver/Chart.yaml
- add-ons/aws-for-fluent-bit/Chart.yaml
- add-ons/cert-manager/Chart.yaml
- add-ons/cluster-autoscaler/Chart.yaml
- add-ons/external-dns/Chart.yaml
- add-ons/ingress-nginx/Chart.yaml
- add-ons/karpenter/Chart.yaml
- add-ons/keda/Chart.yaml
- add-ons/kubernetes-dashboard/Chart.yaml
- add-ons/metrics-server/Chart.yaml
- add-ons/prometheus/Chart.yaml
- add-ons/spark-operator/Chart.yaml
- add-ons/traefik/Chart.yaml
- add-ons/vpa/Chart.yaml
- add-ons/yunikorn/Chart.yaml
> Update chart versions

- add-ons/ondat/Chart.yaml
N/A
Upgrades Ondat addon to use chart version `0.0.6`, Ondat version `v2.8.0`
> Update Ondat addon

- add-ons/external-secrets/Chart.yaml
- chart/Chart.yaml
- chart/templates/external-secrets.yaml
- chart/values.yaml
Add the external-secrets operator to the addons. To partner with https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/612
> Add External Secrets Operator

- add-ons/kyverno/Chart.yaml
- add-ons/kyverno/values.yaml
Add [Kyverno](https://kyverno.io/) adon
> Add-on for the kyverno 

- add-ons/cluster-autoscaler/Chart.yaml
https://github.com/kubernetes/autoscaler/releases
> chore: patch cluster-autoscaler version

- chart/templates/agones.yaml
- chart/templates/appmesh-controller.yaml
- chart/templates/argo-rollouts.yaml
- chart/templates/aws-calico.yaml
- chart/templates/aws-cloudwatch-metrics.yaml
- chart/templates/aws-efs-csi-driver.yaml
- chart/templates/aws-for-fluent-bit.yaml
- chart/templates/aws-load-balancer-controller.yaml
- chart/templates/aws-otel-collector.yaml
- chart/templates/cert-manager.yaml
- chart/templates/cluster-autoscaler.yaml
- chart/templates/external-dns.yaml
- chart/templates/external-secrets.yaml
- chart/templates/gatekeeper.yaml
- chart/templates/ingress-nginx.yaml
- chart/templates/karpenter.yaml
- chart/templates/keda.yaml
- chart/templates/kube-state-metrics.yaml
- chart/templates/kubernetes-dashboard.yaml
- chart/templates/metrics-server.yaml
- chart/templates/ondat.yaml
- chart/templates/prometheus.yaml
- chart/templates/spark-operator.yaml
- chart/templates/tetrate-istio.yaml
- chart/templates/traefik.yaml
- chart/templates/vpa.yaml
- chart/templates/yunikorn.yaml
- chart/values.yaml
Block by https://github.com/aws-samples/eks-blueprints-add-ons/pull/60 because conflicts
- Closes #21
- Closes #26
> feat: Allow Passthrough of Helm values in All Helm Charts

- add-ons/promtail/Chart.yaml
- chart/templates/promtail.yaml
- chart/values.yaml
Add the grafana  promtail addon linked to https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/898
> feat: Add grafana Promtail

- add-ons/kubecost/Chart.yaml
- add-ons/kubecost/values.yaml
- chart/templates/kubecost.yaml
- chart/values.yaml
Description of changes:
Add the kubecost addon linked to https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/901
> feat: Add kubecost

- add-ons/chaos-mesh/Chart.yaml
- chart/templates/chaos-mesh.yaml
- chart/values.yaml
Add the chaos-mesh addon linked to https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/929
> feat: Add chaos-mesh

- add-ons/smb-csi-driver/Chart.yaml
- chart/templates/smb-sci-driver.yaml
- chart/values.yaml
Add the smb-csi-driver addon linked  https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/930
> feat: Add smb-csi-driver

- add-ons/cilium/Chart.yaml
- add-ons/cilium/values.yaml
- chart/templates/cilium.yaml
- chart/values.yaml
Description of changes:
Add the cilium addon linked to https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/920
> feat: Add cilium

- add-ons/reloader/Chart.yaml
- chart/templates/reloader.yaml
- chart/values.yaml
Add the GitOps config for the Reloader add-on, recently merged: https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/931
> Add reloader GitOps configuration

- chart/values.yaml
Added clusterName to values.yaml for gatekeeper support
> Added clusterName to gatekeeper values

- add-ons/cert-manager-csi-driver/Chart.yaml
- chart/templates/cert-manager-csi-driver.yaml
- chart/values.yaml
Adds the Cert Manager CSI driver corresponds to https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/945
> Add cert-manager CSI driver

- add-ons/nvidia-device-plugin/Chart.yaml
- chart/templates/nvidia-device-plugin.yaml
- chart/values.yaml
See https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/995
> feat: add-on for nvidia-device-plugin

- chart/templates/argo-rollouts.yaml
- chart/templates/kube-state-metrics.yaml
- chart/templates/kubernetes-dashboard.yaml
> remove hardcoded repoURL

- add-ons/kyverno/Chart.yaml
- add-ons/kyverno/values.yaml
- chart/values.yaml
*Issue #, if available:* 
https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/910#discussion_r972374897
*Description of changes:* 
- Updated the version of Kyverno
- Added enable flag for policies and reporter
- Added the policies and reporter dependencies
> Updated Kyverno Chart and Values

- add-ons/argo-workflows/Chart.yaml
- chart/templates/argo-workflows.yaml
- chart/values.yaml
> argo workflows

- chart/templates/kubecost.yaml
*Issue #, if available:* #111 
*Description of changes:* Allow the ArgoCD Application to create the KubeCost namespace automatically
> Create namespace for Kubecost

- add-ons/velero/Chart.yaml
- chart/templates/velero.yaml
- chart/values.yaml
https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1128
- add basic config for velero support (additional config may be required for full e2e workflow)
> Add velero

- chart/templates/tetrate-istio.yaml
*Issue #118*
*Enabled auto creation of namespace in argocd app for tetrateisio adds_on*
> add syncoptions for tetrateistio app

- add-ons/external-dns/Chart.yaml
fix chart name for "external-dns"
Signed-off-by: Pratik Raj <Rajpratik71@gmail.com>
> chore: fix chart name for "external-dns"

- add-ons/thanos/Chart.yaml
- chart/templates/thanos.yaml
- chart/values.yaml
Adding Thanos gitops configuration
> adding thanos

- add-ons/vault/Chart.yaml
- add-ons/vault/values.yaml
- chart/templates/tetrate-istio.yaml
- chart/templates/vault.yaml
- chart/values.yaml
*Issue #120*
*Added new addon "Hashicorp Vault" based on the existing structure of the repo i.e. 
chart
├── templates
│        └── vault.yaml      **<-- New**
├── values.yaml         **<-- Updated**
add-ons
├── vault                    **<-- New**
│   └── Chart.yaml     **<-- New**
│   └── values.yaml    **<-- New**
*
> Adding Hashicorp Vault Addon

- chart/templates/kube-state-metrics.yaml
Updating chart to include CreateNamespace
> Updating kube state metrics chart to include CreateNamespace

- add-ons/otel-collector-argocd/Chart.yaml
- add-ons/otel-collector-argocd/values.yaml
- add-ons/prometheus-node-exporter/Chart.yaml
- add-ons/prometheus-node-exporter/values.yaml
- chart/templates/otel-collector-argocd.yaml
- chart/templates/prom-node-exporter.yaml
- chart/values.yaml
issue #138 
Adding prometheus node exporter addon to support observability examples. 
> Adding Prometheus Node Exporter addon 

- add-ons/aws-cloudwatch-metrics/values.yaml
- add-ons/aws-for-fluent-bit/values.yaml
- add-ons/karpenter/Chart.yaml
- add-ons/karpenter/values.yaml
- add-ons/kubecost/values.yaml
- chart/Chart.yaml
- chart/templates/karpenter.yaml
- chart/values.yaml
Also add tolerations all for aws-for vluentbit and cloudwatch so that they can be install on taints nodes.
> Update Karpenter to v0.22.1

- add-ons/consul/Chart.yaml
- add-ons/consul/values.yaml
- chart/templates/consul.yaml
- chart/values.yaml
See https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1029
> feat: add-on for consul

- add-ons/calico/values.yaml
> chore: set tigera-operator installation.kubernetesProvider=EKS

- argocd/bootstrap/control-plane/addons/aws/addons-aws-cloudwatch-metrics-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-csi-efs-driver-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-csi-fsx-driver-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-fluentbit-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-gateway-api-controller-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-load-balancer-controller-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-node-termination-handler-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-cert-manager-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-cluster-autoscaler-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-external-secrets-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-karpenter-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-privateca-issuer-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-velero-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-secrets-store-csi-driver-provider-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-argo-cd-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-argo-events-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-argo-rollouts-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-argo-workflows-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-cert-manager-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-cluster-proportional-autoscaler-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-crossplane-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-gatekeeper-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-gpu-operator-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-kube-prometheus-stack-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-kyverno-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-metrics-server-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-prometheus-adapter-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-secrets-store-csi-driver-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-vpa-appset.yaml
Fixes #163 
fix {{metadata.annotations.addons_repo_basepath}} to be argocd/
> fix {{metadata.annotations.addons_repo_basepath}} to be argocd/

- argocd/bootstrap/control-plane/addons/aws/addons-aws-csi-ebs-resources-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-fluentbit-fargate-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-argocd-hub-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-argocd-ingress-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-crossplane-providers-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-external-dns-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-ingress-nginx-appset.yaml
- argocd/bootstrap/control-plane/addons/oss/addons-kyverno-appset.yaml
- argocd/charts/addons/argo-cd/values.yaml
*Issue #, if available:* FIX #165
*Description of changes:* Add prefix so that we can reference to the appropriate path
> [argocd] Fix value files

- argocd/bootstrap/control-plane/addons/aws/addons-aws-gateway-api-controller-appset.yaml
- argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-karpenter-appset.yaml
> Fix gateway account
